name: revup_admin
description: A Very Good App
version: 0.0.1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  auto_route: ^4.0.1
  dartz: ^0.10.1
  fluent_ui: ^3.9.1
  fluentui_system_icons: ^1.1.177
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_form_builder: ^7.3.1
  flutter_form_field_validator: ^1.0.0
  freezed_annotation: ^2.0.3
  intl: ^0.17.0
  json_annotation: ^4.5.0
  revup_core:
    git:
      url: https://github.com/Revup-vn/revup-core.git
      ref: main

dev_dependencies:
  build_runner: ^2.1.11
  dart_code_metrics: ^4.17.0
  dependency_validator: ^3.2.2
  freezed: ^2.1.0+1
  import_sorter: ^4.6.0
  json_serializable: ^6.3.1
  very_good_analysis: ^3.0.1

import_sorter:
  comments: false
