name: revup_admin
description: A Very Good App
version: 1.2.1-pre
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  auto_route: ^5.0.1
  bloc_concurrency: ^0.2.0
  cached_network_image: ^3.2.2
  carousel_slider: ^4.1.1
  dartz: ^0.10.1
  flash: ^2.0.3+3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_form_builder: ^7.3.1
  form_builder_validators: ^8.3.0
  freezed_annotation: ^2.0.3
  hydrated_bloc: ^9.0.0-dev.2
  intl: ^0.17.0
  json_annotation: ^4.6.0
  revup_core:
    # git:
    #   url: https://github.com/Revup-vn/revup-core.git
    #   ref: main
    #   version: ^6.3.10
    path: packages/injected/revup-dev
  rxdart: ^0.27.5
  shimmer: ^2.0.0

dev_dependencies:
  auto_route_generator: ^5.0.1
  build_runner: ^2.1.11
  dart_code_metrics: ^4.17.0
  dependency_validator: ^3.2.2
  flutter_test:
    sdk: flutter
  freezed: ^2.1.0+1
  import_sorter: ^4.6.0
  json_serializable: ^6.3.1
  very_good_analysis: ^3.0.1

import_sorter:
  comments: false

flutter:
  uses-material-design: true
